name: Notify Slack

on: workflow_dispatch

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    steps:
    - name: Notify Slack
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        text: 'Testing a new slack action'
